/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pak;
import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.event.ActionListener;
import static java.lang.Integer.*;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author George
 */

// ver. 0.0.1

public class alpha1 extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form alpha1
     */
    //декларация на полета
    private JPanel p1, fields1, fields2, fields_opt;
    private ramo1Paint pic;
    private JLabel begin, in_lb, grad_lb, opt_lb, lng1_lb, lng2_lb;
    private JTextField intf, lngt1_tf, lngt2_tf;
    private JButton check;
    
    public alpha1() {
        super("stava");
        //initComponents();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        Container container = this.getContentPane();
        container.setLayout(new FlowLayout(FlowLayout.CENTER));
        //header
        p1 = new JPanel();
        begin = new JLabel("Изобразяване на ъгъл от става");
        p1.add(begin);
        container.add(p1);
        //изображение
        pic = new ramo1Paint();
        pic.setPreferredSize(new Dimension(400,600));
        pic.setBorder(BorderFactory.createLineBorder(Color.black));
        container.add(pic);
        //входни полета за градус
        fields1 = new JPanel();
        in_lb = new JLabel("Въведете число от 0-255 :");
        fields1.add(in_lb);
        intf = new JTextField(); 
        intf.setPreferredSize(new Dimension(100,25));
        check = new JButton("ok");
        check.addActionListener(this);
        grad_lb = new JLabel("Става 1 има ъгъл от : ");
        fields1.add(intf);
        fields1.add(check);
        fields1.add(grad_lb);
        container.add(fields1);
        //за дължини
        fields2 = new JPanel();
        fields2.setLayout(new GridLayout(2,2) );
        fields_opt = new JPanel();
        fields_opt.setPreferredSize(new Dimension(4000,25));
        opt_lb = new JLabel("Въведете дължина на (в pxl):");
        lng1_lb = new JLabel("рамо Р1");
        lngt1_tf = new JTextField();
        lngt1_tf.setText("100");
        lngt1_tf.setPreferredSize(new Dimension(100,25));
        lng2_lb = new JLabel("рамо Р2");
        lngt2_tf = new JTextField ();
        lngt2_tf.setText("100");
        lngt2_tf.setPreferredSize(new Dimension(100,25));
        fields_opt.add(opt_lb);
        fields2.add(lng1_lb);
        fields2.add(lngt1_tf);
        fields2.add(lng2_lb);
        fields2.add(lngt2_tf);
        container.add(fields_opt);
        container.add(fields2);
        //размер и видимост (финализиране)
        this.setSize(600,900);
        this.setVisible(true);
    }
    @Override
    public void actionPerformed(java.awt.event.ActionEvent e) {
        int degtake, lngt_of1, lngt_of2;
        try {
            Object source = e.getSource();
            if (source == check) {
                //парсваме данните от TXTfields 
                degtake = parseInt(intf.getText());
                lngt_of1 = parseInt(lngt1_tf.getText());
                lngt_of2 = parseInt(lngt2_tf.getText());
                //създаваме обект за кал. 
                degrecalc ramo2 = new degrecalc(degtake,lngt_of2);
                grad_lb.setText("Става 1 има ъгъл от : " + ramo2.getDegree());
                //сетваме променливите в изображението
                pic.setStick1(lngt_of1);
                pic.setStick2(lngt_of2);
                pic.setStick2x2(ramo2.getX());
                pic.setStick2y2(ramo2.getY());
                pic.setdegre(ramo2.getDegree());
                //попринцип става автоматично но за всеки случеи изискваме repaint
                this.repaint();
            }
        } catch (Exception exc) {
            //изписва грешката в систем конзолата и в popup прозорец
            System.out.println(exc);
            JOptionPane.showMessageDialog(this, exc, "ERROR",JOptionPane.OK_OPTION);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new alpha1().setVisible(true);
            }
        });
    }

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
